# Generated by Django 3.2.4 on 2021-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('publishingYear', models.IntegerField()),
                ('publisherName', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'book deteail',
            },
        ),
    ]
