# Generated by Django 3.2.4 on 2021-07-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookproduct',
            old_name='name',
            new_name='bookName',
        ),
    ]
